#nom de l'app
spring.application.name=Spring Docker
# l'url de la base de données
spring.datasource.url=jdbc:mysql://localhost:3306/demo_db?createDatabaseIfNotExist=true
# root
spring.datasource.username=root
# aucun password
spring.datasource.password=
# update
spring.jpa.hibernate.ddl-auto=update
# port car le 8080 est deja en utilisation chez moi
server.port=8081
